### ISSUE TITLE
crash on sxOS

### ISSUE THREAD

**Issue by RadYio** [tallbl0nde/NX-Activity-Log#10]
Error code: 2168-0002
"Oops! something went wrong.
Your switch ran into a problem and need to restart.
To restart SX OS press the POWER button."
SXOS : 2.9.2 / firmware : 9.0.1

**Comment by tallbl0nde** [comment]
I'm not planning to support sxos specific errors, but can I ask what you were doing when it crashed?

**Comment by RadYio** [comment]
Nothing just started this home brew

**Comment by tallbl0nde** [comment]
Did you launch it through a title or the album? It only works through a title. Also note that I won't debug this as I don't want to run sxos on my switch.

**Comment by RadYio** [comment]
Ok btw I don’t know how to use through a title, I only use album and homebrew to use them.

**Comment by Conan179** [comment]
This is the error.
You must runn it as NSP injekt.
Start a game with pressing R and now you can open NX-Activity-Logwithout error.

**Comment by tallbl0nde** [comment]
Thanks @Conan179, I was just typing that out! Let me know if that fixes the crash and then we can close the issue :)

**Comment by tallbl0nde** [comment]
I'm going to assume that's fixed the problem so I'll close the issue.
