### ISSUE TITLE
Unable to get a User ID

### ISSUE THREAD

**Issue by ardyn60** [tallbl0nde/NX-Activity-Log#11]
Hi, I have this error code when I try to launch NX activity log. It may be related to my user account  that have never been connected to internet or linked to a nintendo account. Thanks for your help.

**Comment by tallbl0nde** [comment]
I've tested it with newly created accounts on my banned switch (so they definitely aren't linked) and they work fine. Just double checking, are you launching through the album or a game?

**Comment by ardyn60** [comment]
I launch it through the album, is there an other way to launch ? For information, I can't see my played time even in my profile.

**Comment by tallbl0nde** [comment]
Version 1.0.0 doesn't work through the album unfortunately. Luckily you've got a few options:
1 - Launch using a title (hold R when launching a game to launch hbmenu OR use a hbmenu nsp)
2 - Use Atmosphere 0.10.0 (it fixes this problem)
3 - Wait for my next update which will work in the album

**Comment by ardyn60** [comment]
Works perfectly since atmosphere update. Thanks
