### ISSUE TITLE
Hard shutdown while quickly scrolling through days

### ISSUE THREAD

**Issue by oracleofire** [tallbl0nde/NX-Activity-Log#12]
On 9.0.1 | AMS 10.1, oogling at all the fascinating data through this application (applet mode). Filtered activity by day and rapidly scrolled maybe a year back when the screen turned off (I was docked, dock light still on), no crash screen, just an unresponsive switch. For all intents and purposes it seemed to be shutdown (did not wake up when taken off dock) and required a reboot. 

Not really sure what happened, not even sure if the issue is reproducible, so I don't know if this is even helpful. I thought I'd just put down my experience here anyway. I've had my share of crashes, but first time having the Switch hard shutdown.

Also! Unrelated, but a quicker way to scroll through days would be great. Such as holding down a button, or a separate submenu that lets you select the exact day. I really like what you've made!

**Comment by tallbl0nde** [comment]
That's interesting, I've only ever experienced that after many repeated launches when I've been developing it and only in title mode. My switch does that when the app launches though, I haven't ever had it happen while I've been navigating through it... I don't know how to go about debugging this :/

And yep I'm planning to improve/redo how you browse through your recent activity, I know it's quite a pain at the moment. Glad you like it and there will be even more data to view down the track! :)

**Comment by pandavova** [comment]
Related to the browsing through the activity: 
Something like L/R to switch through the sorting modes and ZL/ZR to progress the activity by the number of entities onscreen (currently 4).
Also iMo it prolly would be better to just include a specific number of games on the screen so nothing is cut off, currently its like 4 and a half entries.

**Comment by tallbl0nde** [comment]
Over the last 2 months I haven't encountered this random freeze so I'm going to bet I've fixed it somehow in the rewrite!
