### ISSUE TITLE
CFW no longer boots after enabling Menu Override

### ISSUE THREAD

**Issue by Auriosi** [tallbl0nde/NX-Activity-Log#13]
CFW: Atmosphere 0.10.1
OFW: 9.1.0
When I enabled something along the lines of a menu override, I went to check it out, but when just opening my profile, Atmosphere threw an error. I rebooted but it gave an error again. I know that sometimes, just deleting the app works, but I don't know what else to delete after removing the NRO. Is there a way I could fix this and at least boot back into CFW without a fresh reinstall of Atmosphere? I've also tried just pasting a new Atmosphere folder in the root and overwriting whatever was there.

**Comment by tallbl0nde** [comment]
All my app does is add a file within atmosphere/contents/0100000000001013 so if you delete that folder you should be able to get back into atmosphere and the user page. Note this will also remove any themes you applied to the user page.

The only reason I'm aware of that causes it to crash is that the .nro is not in the correct position. It should be at /switch/NX-Activity-log.nro
In the next update I'll improve this feature as it's gotten quite a few people confused!

**Comment by Auriosi** [comment]
After deleting that folder, I still have a fatal error message from Atmosphere.

**Comment by tallbl0nde** [comment]
It must be something else then, as after removing the .nro and that folder there's no traces of the app anymore.

**Comment by Auriosi** [comment]
I decided to switch (see what I did there?) to a different CFW, Kosmos. I'm probably not going to install again, unfortunately, because I'd probably be stupid and break it again. Sorry, but great piece of homebrew!
