### ISSUE TITLE
Error occurs when overriding user page

### ISSUE THREAD

**Issue by reannu123** [tallbl0nde/NX-Activity-Log#14]
Greetings! 

I have sx os 2.9.3 (EDIT: I'm on 9.1.0) emunand and when I go into the settings menu in applet mode and try to enable override user page, it crashes and it requires pressing the power button to restart. 

I even tried non-applet mode and a different crash screen occurs (where an option to share or not share is given) but it does not restart the system.

**Comment by tallbl0nde** [comment]
Hmm, all it does is copy a file into a folder so I find it weird that it's crashing. I have no idea how SX OS works, but do you have the /sxos/titles folder on your sd card?

**Comment by reannu123** [comment]
Hmm that does sound weird. And yes I do, I guess I'll try deleting the sxos/titles folder, or I'll try a different SD card, or I'll try using fat32 as I am currently using exfat. 

I'll update you in 8 hours.

Thanks!

**Comment by reannu123** [comment]
Update 1: Okay so i deleted the titles folder and the error does not occur, but it does not do anything. It does not create a 'titles' folder. But when I created a new titles folder, the crash happened again.

**Comment by tallbl0nde** [comment]
Thanks for all the updates, I'm not sure why SX would cause it to not work. I'll look at improving the "installation" side of things to report errors in an update, but I still find it weird that it causes the system to crash.

**Comment by reannu123** [comment]
Yeah it is weird. I wonder if it works with older versions of SX OS, I can't try because of fuses. 
Glad to have helped!

**Comment by tallbl0nde** [comment]
TX must have done something which for some reason messes this up then (or me lol). Like I said I'll change how this works in the future and hopefully resolve this, however I'll close the issue seeing as I'm not going to heavily debug SX OS specific problems. That being said I hope it's fixed (either by me or TX) at some point!

Also thank you so much for all the testing and updates, I wish everyone would do that! :D

**Comment by tallbl0nde** [comment]
Just thought about this (note to self I guess):
This could most likely be due to it not being able to read the file from romfs, or perhaps the new libnx update has messed things up with sx

**Comment by reannu123** [comment]
Thanks! I hope it get fixed soon but it's just a minor inconvenience so no biggy, and sure no problem! Thanks for the app :)
