### ISSUE TITLE
Crash when launching overridden profile

### ISSUE THREAD

**Issue by iomintz** [tallbl0nde/NX-Activity-Log#15]
I'm using Atmosphere 0.10.2 and launching NXActivityLog in non-applet mode. Enabling "override user page" works fine, but when I open the profile, I get an Atmosphere system crash which requires pressing a volume button.

Error code: 2347-0003 (0x75b)
Program: 0100000000001013
Firmware: 9.1.0 (Atmosphère 0.10.2-master-d5458960

None of the CPU registers have their values listed. The program counter is 0 and so is the backtrace start address and all of the backtrace frames.

**Comment by tallbl0nde** [comment]
This error appears to be a homebrew-specific error. My guess is that the .nro isn't at the expected location - it should be at /switch/NX-Activity-Log.nro and thus the loader crashes as it can't find the file.

**Comment by iomintz** [comment]
I installed it through the Homebrew App Store. Do you have control over where it places the nro?

**Comment by tallbl0nde** [comment]
I don't think so, it appears it always puts it in a folder. I didn't realize this but I'll set everything up so that is has to be in a folder next update and it also checks beforehand to avoid this problem.
