### ISSUE TITLE
If you go "Recent Activity", put your joystick to right, scroll down and spam "A" it crashes

### ISSUE THREAD

**Issue by pandavova** [tallbl0nde/NX-Activity-Log#16]
I don't really know how I found it, I just reproduced it like this.
It also doesn't matter if its nro or the replaced user page info.

2168-0002 (0x4a8), 9.0.1 (Atmosphère 0.12.2-master-d5458960)

**Comment by tallbl0nde** [comment]
Good job finding this one, I never would have tried anything like this during testing!

I've been rewriting the UI side of things so it should be fixed when I merge that in. I'll double check for this specific case though!

**Comment by tallbl0nde** [comment]
Fixed in recent update :)
