### ISSUE TITLE
Feature Concept for graph

### ISSUE THREAD

**Issue by Shadas4free** [tallbl0nde/NX-Activity-Log#19]
I´ve build your latest version of this app and it´s look better and better. Very nice job with this one. Do you planning to add some graph activity per month/year? I have uploaded some concept to understand it better :-)

![graph](https://user-images.githubusercontent.com/61040455/74505502-96ac8a00-4ef7-11ea-91dd-529b0eb1c360.jpg)
![template](https://user-images.githubusercontent.com/61040455/74505505-97ddb700-4ef7-11ea-93c2-066d09524793.jpg)

**Comment by tallbl0nde** [comment]
They're some pretty nice concepts! That's actually the only thing left that I want to do before releasing a new version. I'm not sure if I'll add it as a separate tab/screen like that; but either way it'll be added soon :)

**Comment by tallbl0nde** [comment]
Added in the latest release!
