### ISSUE TITLE
[Request] Include activity of deleted games

### ISSUE THREAD

**Issue by Dantenerosas** [tallbl0nde/NX-Activity-Log#2]
After trying out the app I can say that it is rather good even in it's current state but I couldn't help but notice that it doesn't show activity of deleted games. Is it possible to include them for the sake of accuracy and completeness of activity log?

**Comment by tallbl0nde** [comment]
Yep! It's on the to-do list, I somehow didn't notice deleted games weren't included when I was testing it. Should be a simple fix.

**Comment by tallbl0nde** [comment]
The latest commit fixes this and thus deleted games will be shown in the next release :)
