### ISSUE TITLE
NX-Activity-Log doesn't remember your settings 

### ISSUE THREAD

**Issue by reinzanini** [tallbl0nde/NX-Activity-Log#23]
How to make the app remember my preferences? For example: I want it to open on the "All Activity" panel instead of the "Recent Activity" one and sort "by year" instead of "by day". However, it always reverts to the default settings at every startup.

**Comment by tallbl0nde** [comment]
I'll add some options for this on the settings page, as if I have it keep track of what page you left it on it would cause a large number of unnecessary writes to the sd card

**Comment by reinzanini** [comment]
Yeah, some options in the settings would be perfect. Thank you very much.

**Comment by tallbl0nde** [comment]
Added in the latest update! :)
