### ISSUE TITLE
Cannot show Korean characters

### ISSUE THREAD

**Issue by uaevuon** [tallbl0nde/NX-Activity-Log#24]
![2020022203105800-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/75059939-4948a200-5521-11ea-9aa5-47cc11909cb8.jpg)

I think CJK font is missing.

**Comment by tallbl0nde** [comment]
Hmm this is interesting as it's using the fonts directly on the switch and not my own files. I'll look into it!

**Comment by uaevuon** [comment]
I have no skill or knowledge and don't know if this is helpful or not, but i just leave these here.
https://github.com/DarkMatterCore/nxdumptool/issues/36
https://github.com/DarkMatterCore/nxdumptool/commit/ba6b483cb690bccd1a43b87734683e7c1c54d8c2

This homebrew also had similar issue and fixed in v1.1.5.

**Comment by tallbl0nde** [comment]
Those links were helpful! I think I know how to fix it, no idea how long it will take though.

**Comment by tallbl0nde** [comment]
@uaevuon or someone else - I believe I've added support for all characters now. It's worked fine during testing but I'd just like to double check that it works for game titles. Could you please see if the characters appear with the attached .nro?

[NX-Activity-Log.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4501769/NX-Activity-Log.zip)

**Comment by uaevuon** [comment]
![2020042017472600-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/79732842-33900700-832f-11ea-976d-a1ffdc2439da.jpg)
![2020042017522600-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/79733364-ef513680-832f-11ea-8d5c-7132eaa28bed.jpg)

Want to check but can't. Nothing appears.
From v1.1.0 to the above one, it does not show anything.

v1.0.0 is fine. 
![2020042018045200-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/79734336-84086400-8331-11ea-922f-45a47361c34b.jpg)

I'm on 10.0.0, AMS 0.11.1.

**Comment by tallbl0nde** [comment]
Give this one a try...
[NX-Activity-Log.zip](https://github.com/tallbl0nde/NX-Activity-Log/files/4502458/NX-Activity-Log.zip)

**Comment by uaevuon** [comment]
![2020042018343900-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/3542715/79737124-d21f6680-8335-11ea-9dd7-5bb5cbfa2fd6.jpg)

Thanks, it works!


BTW it's just my opinion.
I think you better to make About under Settings and put your kofi link, homebrew version and update option there, instead of bottom of Settings.

**Comment by tallbl0nde** [comment]
Thanks for testing!! 

Yeah I was thinking of doing something like that but I'm not too sure. I probably will eventually :P
