### ISSUE TITLE
Override user page + custom theme on user page causes Atmosphere crash

### ISSUE THREAD

**Issue by Stuntaneous** [tallbl0nde/NX-Activity-Log#25]
Just a notice of this happening, really. If possible, perhaps you could catch the problem before Atmosphere crashes and provide a warning and exit.

**Comment by Stuntaneous** [comment]
It may actually be more than I described. Uninstalling the theme and deleting the titles/contents folders (1000, 1013) doesn't fix the issue.

Error Code: 2347-0003
Program: 0100000000001013
Firmware: 9.1.0 (Atmosphere 0.10.2)

**Comment by tallbl0nde** [comment]
This error indicates that the .nro couldn't be found. Did you perhaps have the replace feature installed by v1.1.0 and then updated to 1.2.0? Either way I'd recommend disabling/uninstalling it from within the all and then enabling it again and see if it fixes it

**Comment by tallbl0nde** [comment]
Seeing how there's been no response for a month I'm going to close the issue. If this problem is still occurring please reopen or open another one!
