### ISSUE TITLE
NX-Activity-Log seems to be ignoring the current timezone set on Horizon OS

### ISSUE THREAD

**Issue by evertonstz** [tallbl0nde/NX-Activity-Log#27]
I'm currently located in timezone UTC/GMT -3 hours. My play time length seems to be fine and precise, the problem is that when displayed on NX-A-L my data is shown as if I was located in UTC/GMT +00 hours, this means everything is skewed 3 hours to the future.

Don't know if it's possible to pull this data from the operating system, if not an option to set the timezone manually in NX-A-L settings should be the second best option! 

Cheers!

**Comment by tallbl0nde** [comment]
Are you using version 1.2.1? If so it appears I've introduced a bug that causes issues like these which I haven't gotten around to fixing yet. All my data shows the correct times with my Switch set to my timezone (+9:30) so I doubt it's strictly a timezone issue.

**Comment by evertonstz** [comment]
Yes, it's 1.2.1, just double checked. I probably should add that I'm using the layeredFS option to replace the profile menu for NX-A-L.
I'm gonna downgrade the software to see if the problem persists and will report the results here soon!

**Comment by tallbl0nde** [comment]
Cheers! Yeah I really messed up with the release of 1.2.1, I shouldn't have tested it at 11pm at night :P

**Comment by evertonstz** [comment]
Strangely enough the bug seems to exist on 1.2.0 and 1.1.0 here too, could be this is a bug on horizon or atmosphere trickling down to NX-A-L?

**Comment by tallbl0nde** [comment]
Oh I was hoping it was something dumb I did :/

I have no idea now... I would assume it's something I've done but it's just strange no one has reported anything similar before. I'll have to look into it! 

You haven't changed your timezone due to travelling or anything? Only asking because maybe changing the timezone is the cause of the issue.

**Comment by evertonstz** [comment]
> 
> 
> Oh I was hoping it was something dumb I did :/
> 
> I have no idea now... I would assume it's something I've done but it's just strange no one has reported anything similar before. I'll have to look into it!
> 
> You haven't changed your timezone due to travelling or anything? Only asking because maybe changing the timezone is the cause of the issue.

No I didn't, but I think I'm starting to get to the bottom of the problem, I just noticed HBmenu also has a clock and this one is also 3 hours on the future. So it's confirmed not a problem on NX-A-L at all, seems to be a [bug on libnx](https://gbatemp.net/threads/how-to-change-hbmenu-to-the-correct-time-zone-as-switch.553221/) for certain timezones!

**Comment by tallbl0nde** [comment]
Oh right! I've had a look into a few things and yep it's definitely a libnx issue. I don't know how to build against any other libnx version other than the official release otherwise I'd try compiling a new .nro for you... sorry!

**Comment by evertonstz** [comment]
No problems, mate. It seems the bug is already [closed](https://github.com/switchbrew/libnx/commit/f043307e7f580f6507f4285c898c6ac725bb364f) since Dec/19/19 so the the 3.0.0 release from Dec/10/19 didn't pick this commit up. It'll come in their next release for sure, it's not that big of a deal so I can wait fine for it :D
