### ISSUE TITLE
[Feature request] Update in-app

### ISSUE THREAD

**Issue by reinzanini** [tallbl0nde/NX-Activity-Log#28]
Add option to check for updates automatically and then update in-app

**Comment by tallbl0nde** [comment]
That's a good idea, it should be easy enough to add as part of the next update!

**Comment by galego83** [comment]
Hey tall, 
Some apps are able to check for updates only. But implementing both  check AND update within the app is one of the coolest features. 
Thank you for your work!!

**Comment by tallbl0nde** [comment]
Added and will be available in the next update within the next few days!
