### ISSUE TITLE
100 games limit

### ISSUE THREAD

**Issue by inCrooo** [tallbl0nde/NX-Activity-Log#3]
I know this is a very unique issue but I thought it's worth mentioning. I have more than 100 games installed (400GB SD card). But it only shows the last 100 games played.

For example, I played the hell out of ARMS. But the last time I played it was more than a year ago so it doesn't show up in most played at all.

**Comment by tallbl0nde** [comment]
That was an arbitrary limit I forgot to remove before release (whoops). The good news is that this will be fixed in the next release (fixed in the latest commit)
