### ISSUE TITLE
"Titles played" list empty

### ISSUE THREAD

**Issue by iomintz** [tallbl0nde/NX-Activity-Log#35]
The All Activity list is empty for me, and there's nothing below the Recent Activity graph, although the graph itself is fine.

HOS 10.0.0
AMS 0.11.1
NX Activity Log v1.2.2

**Comment by tallbl0nde** [comment]
This is due to a change in 10.0.0 - I've fixed it already in another issue so I'll leave this one open until I actually release the update so others know!

**Comment by ShotSkydiver** [comment]
Latest code in master works great on 10.0.0! Pulled down the github repo and built the app manually!

![0Q4L](https://user-images.githubusercontent.com/2718920/80180828-d1e6cb80-85c0-11ea-89ee-622a4b5ebaed.jpg)

**Comment by tallbl0nde** [comment]
Closing as I've released the update!
