### ISSUE TITLE
Feature Request: Flag to disable including activity of deleted games

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [tallbl0nde/NX-Activity-Log#4]
Something like ``sdmc:/config/nodeleted.flag`` /shrug

I'll PR it myself if you don't want to do it 😉

**Comment by tallbl0nde** [comment]
I'll add it soon™, I just have a lot on at the moment so you're more than welcome to make a PR if I take too long 😉

The only thing I'd add is I'm unsure about the path/file name.  Maybe something like:
- sdmc:/config/NX-Activity-Log/hidedeleted.flag
Just so more config flags/options can be stored in the same folder further down the road.

**Comment by tallbl0nde** [comment]
I've addressed this in the latest commit, I'll just leave the issue open until the next release so others don't make the same request :)
