### ISSUE TITLE
Edit playtime

### ISSUE THREAD

**Issue by ThomasHeaton31** [tallbl0nde/NX-Activity-Log#43]
Hi, recently i had to re-install atmosphere and emummc on a new sd card, because my main one was corrupted. I still have a backup of that old sd card, but the actual card is unusable, i'd just like to know if you could add a way to edit my playtime on the games as my time was reset, because id like to add on the extra hours that i originally had. i would also like to know if there is a way to view how long i had played my games from my backup of that sd card. thanks

**Comment by tallbl0nde** [comment]
I'm not intending to edit the play log directly, as I don't think it's possible while Horizon is booted plus I don't want to experiment on my own console. What I'm thinking of is allowing the time shown in the app to be edited, but not the time stored on the system. I don't know when I'll get around to it though.

Not sure if you'd be able to view how long the games on the card were played for as I have no idea how emuMMC works. Someone else may know how to do it though!

**Comment by tallbl0nde** [comment]
Going to close this issue as it's the similar to #5.
