### ISSUE TITLE
Info/profile from one switch to another switch

### ISSUE THREAD

**Issue by 38285760** [tallbl0nde/NX-Activity-Log#44]
Hello! I have a switch with emunand which has 1 profile with more than 300 hours of play. I got a new Switch and I also put Emunand on it.

Is it possible to somehow move the profile (and the hours of play) from one switch to another?

**Comment by tallbl0nde** [comment]
I believe there's an official way to do so? If you don't want to (or can't) connect to the internet, then I don't think there's a proper way to do it, as a lot of account/user data files are unwritable while Horizon is running.

If you're referring to the app doing it, the closest thing that will be implemented is a backup/restore _within the app_, (ie. it won't be restored to the official User Page/account). See [this issue](https://github.com/tallbl0nde/NX-Activity-Log/issues/21) for more info on that side of things.

**Comment by 38285760** [comment]
> I believe there's an official way to do so? If you don't want to (or can't) connect to the internet, then I don't think there's a proper way to do it, as a lot of account/user data files are unwritable while Horizon is running.
> 
> If you're referring to the app doing it, the closest thing that will be implemented is a backup/restore _within the app_, (ie. it won't be restored to the official User Page/account). See [this issue](https://github.com/tallbl0nde/NX-Activity-Log/issues/21) for more info on that side of things.

Thanks! I read that replacing some internal files of the emunand (located in system / save) would work but I'm not sure. It really is a shame to lose that information about the 300 hours of play.

**Comment by tallbl0nde** [comment]
I'm no expert, but while it sounds like it _should_ work, my guess is there are a bunch of files that all store important info that 'ties in' with an account which would all need updating (as in not just copy and pasting). Maybe someone who knows more about the Switch than I do can help you out though! :P

If you don't want to lose your playtime, you can wait until I eventually incorporate the backup/restore functionality, however it's likely that won't happen for quite some time still...

**Comment by Pysis868** [comment]
Came here wondering this exact thing, a migration.  Curious how #21 goes, but would want import too..  Sounds like some files are mentioned.  I expected to use HacDiskMount since it sounds like no editing when booted like over USB or FTP.  Hesitated to do any of that in case I overwrote some unique seed data that I would not be able to get back =/.
