### ISSUE TITLE
The user page replacement option crashed on 12.0.2 AMS19.3

### ISSUE THREAD

**Issue by Bec91v** [tallbl0nde/NX-Activity-Log#47]
Hi,
I got this issue as i just updated my firmware and AMS.
May i know what is amissed?

**Comment by BestPig** [comment]
AMS 0.19.3, has a lot of breaking changes. It required to be recompiled with last libnx.
If you want my compiled version, seems to works fine for me (12.0.2 / AMS 0.19.3)

https://shareit.bestpig.fr/file/b6e58c2aeb097f78c9816c941f8710f1d9bbeef9/NX-Activity-Log.zip

**Comment by calipupsr** [comment]
Used your new compiled version and it still doesn't allow User page replacement to be enabled.

**Comment by BestPig** [comment]
> Used your new compiled version and it still doesn't allow User page replacement to be enabled. (On 12.0.2 and 0.19.3)

The replacement is working fine for me, maybe you have file from the old version?
Try to to remove `contents/0100000000001013` and re-enable user replacement.

**Comment by calipupsr** [comment]
I made sure I'm using the new .nro. I also don't have that folder on my SD card.

**Comment by Bec91v** [comment]
I tried the recompiled one on both ams 0.19.3 and 0.19.4 on both 12.0.2 and 12.0.3.
It still crashes when i click on the option.

**Comment by Bec91v** [comment]
Close case
