### ISSUE TITLE
JSON export feature request

### ISSUE THREAD

**Issue by profucius** [tallbl0nde/NX-Activity-Log#49]
First of all, love your software. I have a question, I read in the changelog you've added a new JSON export feature. I'm very interested in using this. I wonder if it would be possible to expand this feature from "titles played by the user" to also include an option to export a list of **all installed titles** (or, titles **available** to the current user).

My goal is to have games installed on my Switch as a list on my computer, for use cases such as game organization within a frontend (i.e. Launchbox). I realize that this request may not technically be within scope, but if it were to be not too challenging to add, I would love to have this as a feature! I haven't found this feature in any other homebrew yet (but please inform me if there is one). Thanks!

**Comment by tallbl0nde** [comment]
From the top of my head, this should be possible. I honestly could try writing up a separate .nro that would do what you need as I wouldn't say it fits the scope of NX-Activity-Log. 

Do you just need:
- Title Name,
- TitleID/ProgramID, and
- Icon (stored as JPEG)?

**Comment by profucius** [comment]
Title Name at a bare minimum. However if other data is retrievable and can stored into a text file format like JSON or CSV (and JPG for icons works) whatever is convenient enough, that would be great! 

I had planned to use just the Title Names for my front-end and do some manual retrieval of the missing data pieces, but any other information that's possible would make organization that much easier. For instance, would "Release Date" be possible? Not even sure if that is stored anywhere that can be retrieved by a homebrew like this (without perhaps retrieving and parsing a public titles.json file) but if that type of thing is too complex, then no worries.

**Comment by tallbl0nde** [comment]
I've had a look over the libnx pages and it seems like all the useful data I can get is:
- Name
- Icon (as JPEG as that's how they're stored)
- Author (/publisher?)
- Title/Program ID
- ISBN
- Age Rating
- Version

...and other Switch related flags. The list of metadata is [here](https://switchbrew.github.io/libnx/structNacpStruct.html).

I could put it all in a JSON, then either the icons encoded into the JSON or as separate files... which would be easier for you?

**Comment by profucius** [comment]
Those pieces of data are good. 

I looked through that link, is there one that indicates game installation size? I see some mentioning size but not sure if it's one of these. It would be useful to have a record of which games are the largest, but that's optional.

And JSON for the text is good, but I would think the icons would be better exported as separate files. This way it's easier to parse into my front-end, and there is less risk of the whole JSON becoming corrupted if something hangs during the export, etc. Would it be possible to have the JPG icon filenames be the Title Name of the game?

------------

As I'm typing this I'm thinking of little enhancements, of course these are optional, thinking beyond my own preferences for others who might want to use this. Just some ideas if you're interested to develop this beyond the initial release:

- The types of data (ISBN, Age Rating, etc) can be optionally selected at the time of export, like a screen with checkboxes.
- A choice between JSON and CSV format
- Icons optionally encoded into the JSON
- Icons filenames can be optionally exported as TitleID (for those who prefer that).
- Ability to exclude certain installed titles
- Installation location (NAND vs SD Card) and data size.
- Indicate if the game has a save (indicating if it has been played or not)

**Comment by profucius** [comment]
If I threw too much into a single message I apologize. I hope I didn't overload you. If your time is scarce and you just are able to put out the minimum Title Name export, that would suffice for my needs. Oh and if you decide to create a repo for this, please link me. Thanks!

**Comment by tallbl0nde** [comment]
I've just been busy, I'm just gonna chuck together a .nro that exports a JSON of all installed titles' metadata and then export the icons to files as you've requested. I just offered to do this cause I know how to do so fairly quickly, so I don't wanna make it fancy :P

> I looked through that link, is there one that indicates game installation size?

I don't think so.

**Comment by tallbl0nde** [comment]
Give this a go:
https://github.com/tallbl0nde/TMetaDump/releases/tag/v1.0.0
