### ISSUE TITLE
Feature request  Editing logs

### ISSUE THREAD

**Issue by fennectech** [tallbl0nde/NX-Activity-Log#5]
I would like to be able to edit activity logs because i have some that have lost time somehow   Id like to restore it :)

**Comment by tallbl0nde** [comment]
I'm not sure if that is possible (or if I want this application to do that) just yet, however I could add an "offset" option so that you can increase/decrease the time per game. However, this would only be reflected in my application and not Horizon obviously

**Comment by tallbl0nde** [comment]
Added in v1.4.0!

**Comment by fennectech** [comment]
Holy SH!T
