### ISSUE TITLE
Does it log playtime on game where title override is done?

### ISSUE THREAD

**Issue by bibliophilical** [tallbl0nde/NX-Activity-Log#50]
I was wondering if NX Activity Log logs the time of title that was override as playtime to enter the homebrew menu? Let say I'm using BOTW to enter homebrew menu to play emulators for 2 hours, does it logs 2 hours of BOTW too?

**Comment by tallbl0nde** [comment]
I personally don't use that feature, but from what I've heard from others those 2 hours will be counted as playing BOTW.

**Comment by bibliophilical** [comment]
I see. Thank you very much!
