### ISSUE TITLE
Question regarding Json export and import

### ISSUE THREAD

**Issue by fennectech** [tallbl0nde/NX-Activity-Log#51]
Is importing an exported json writing it back to the switch's internal database?

**Comment by tallbl0nde** [comment]
It doesn't touch the switch's database. It's unwritable while the OS is running (well at least from homebrew) so even if I wanted to I couldn't :)

I thought I'd wrote it under the import button, but it appears I haven't... \*sigh\*

**Comment by fennectech** [comment]
Thanks for the reply.
