### ISSUE TITLE
Curent master branch of Aether is not compatible with master branch of NX-Activity-Log

### ISSUE THREAD

**Issue by m4st3rP** [tallbl0nde/NX-Activity-Log#62]
Running "git submodule update --init", which is necessary to run make, results in the following error:

> $ git submodule update --init
> Submodule 'Aether' (https://github.com/tallbl0nde/Aether) registered for path 'Application/libs/Aether'
> Submodule 'SimpleIniParser' (https://github.com/TehPsychedelic/SimpleIniParser) registered for path 'Application/libs/SimpleIniParser'
> Submodule 'libs/json' (https://github.com/nlohmann/json.git) registered for path 'Application/libs/json'
> Submodule 'Translations' (https://github.com/tallbl0nde/NX-Activity-Log-Translations.git) registered for path 'Application/romfs/lang'
> Cloning into '/home/Philipp/git/NX-Activity-Log/Application/libs/Aether'...
> Cloning into '/home/Philipp/git/NX-Activity-Log/Application/libs/SimpleIniParser'...
> Cloning into '/home/Philipp/git/NX-Activity-Log/Application/libs/json'...
> Cloning into '/home/Philipp/git/NX-Activity-Log/Application/romfs/lang'...
> fatal: remote error: upload-pack: not our ref 6c07fd2e656eb159950fcfdaaa27e8422fc53062
> fatal: Fetched in submodule path 'Application/libs/Aether', but it did not contain 6c07fd2e656eb159950fcfdaaa27e8422fc53062. Direct fetching of that commit failed.

This does not occure with commit d8b92cb848ddc13a4bcefe8bf0b420b215e555bb which is the one version 1.3.2 is based on.

**Comment by tallbl0nde** [comment]
Fixed.
