### ISSUE TITLE
SimpleIniParser moved its repo

### ISSUE THREAD

**Issue by m4st3rP** [tallbl0nde/NX-Activity-Log#63]
It seems the repo is now located at: https://git.nicholemattera.com/NicholeMattera/Simple-INI-Parser instead of https://github.com/AtlasNX/SimpleIniParser. Changing the URL in .gitmodules does not fix a fatal error when running git submodule update --init because the commit history got lost.

See:
> fatal: remote error: upload-pack: not our ref 625d49fb533a7648d4996a7d292ffcd51fb2a61d
> fatal: the remote end hung up unexpectedly
> Fetched in submodule path 'libs/SimpleIniParser', but it did not contain 625d49fb533a7648d4996a7d292ffcd51fb2a61d. Direct fetching of that commit failed.

**Comment by rashevskyv** [comment]
Just git clone this repo to Application/libs instead of SimpleIniParser

**Comment by rashevskyv** [comment]
But even so I got an error while compiling in Aether module

**Comment by rashevskyv** [comment]
I added `"Aether/horizon/Tick.hpp"` to `Application\libs\Aether\include\Aether\Aether.hpp` and compiled NXAL well. But thats all I can do

**Comment by tallbl0nde** [comment]
Both these issues have now been fixed.
