### ISSUE TITLE
no games shown

### ISSUE THREAD

**Issue by WizzStar** [tallbl0nde/NX-Activity-Log#72]
NX Activiy Log is working correctly on my switch, now i placed the same .nro on my gf her switch but no games are showing up.. we did a reboot etc. nothing works, what can we doe to get the games to show up?

**Comment by brlala** [comment]
https://github.com/tallbl0nde/NX-Activity-Log/issues/61#issuecomment-1445377920

Refer to this comment. Do close the issue if it works
