### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lukas2288** [tallbl0nde/NX-Activity-Log#8]
Is it possible display it per day like in WiiU? Some background music would be great ;-)

**Comment by tallbl0nde** [comment]
I'm planning to add some form of daily summary at some point, it could be a while away though.
I'm not sure if I'll add music by default, but I may make it optional!

I'll leave this issue open to remind me to actually do these things :)

**Comment by tallbl0nde** [comment]
I've added a daily summary among other things in the latest version (1.1.0). I've also added music to my to do list so I'll close the issue!
