### ISSUE TITLE
[Crash] on startup

### ISSUE THREAD

**Issue by SegFault42** [tallbl0nde/NX-Activity-Log#9]
The app crash on startup. I just get loading screen then atmosphere crash screen.

Error code : 2003-0008 (0x1003)
Firmware 9.0.0 (Atmosphere 0.9.4-master-c62c4846)

**Comment by tallbl0nde** [comment]
This appears to be an out of memory error. Can I ask roughly how many games you've played on your switch?

**Comment by SegFault42** [comment]
I have 58 titles in total. 

You are right, i tried with nsp version of hb-menu and it's working.
